# Generated by Django 3.2.6 on 2022-05-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Products',
        ),
    ]
