# Generated by Django 3.2.6 on 2022-05-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_items_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
